server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名

aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    keyId: LTAI5tATAyVrrSSYh7z6eV7G
    keySecret: B3UM535xBYaTdY6OWx3eptVvDuFfuc
    bucketName: srb-file-20221221